d /etc/geppetto_server 0750 geppetto-server geppetto-server -
d /etc/geppetto_server/config 0750 geppetto-server geppetto-server -
d /etc/geppetto_server/config/defaults 0750 geppetto-server geppetto-server -
d /etc/geppetto_server/config/groups 0750 geppetto-server geppetto-server -
d /etc/geppetto_server/config/hosts 0750 geppetto-server geppetto-server -
d /etc/geppetto_server/config/templates 0750 geppetto-server geppetto-server -
d /etc/geppetto_server/pki 0750 geppetto-server geppetto-server -
d /etc/geppetto_server/csr_pending 0750 geppetto-server geppetto-server -
d /etc/geppetto_server/certs 0750 geppetto-server geppetto-server -
d /var/log/geppetto 0755 root root -
f /var/log/geppetto/geppetto-server.log 0640 geppetto-server geppetto-server -
